### ISSUE TITLE
[ERROR] "sh" is not a valid Prism.js language for eleventy-plugin-syntaxhighlight

### ISSUE THREAD

**Issue by nlbao** [cdeleeuwe/netlify-plugin-submit-sitemap#18]
Everytime I tried to build & deploy an eleventy blog app with the `submi-sitemap` plugin, this error happened:

```shell
4:03:18 PM: src/main.js → js/min.js...
4:03:19 PM: created js/min.js in 530ms
4:03:21 PM: Language does not exist: sh
4:03:21 PM: Problem writing Eleventy templates: (more in DEBUG output)
4:03:21 PM: > Having trouble rendering liquid (and markdown) template ./.netlify/plugins/node_modules/node-fetch/README.md
4:03:21 PM: `TemplateContentRenderError` was thrown
4:03:21 PM: > "sh" is not a valid Prism.js language for eleventy-plugin-syntaxhighlight
4:03:21 PM: `Error` was thrown:
4:03:21 PM:     Error: "sh" is not a valid Prism.js language for eleventy-plugin-syntaxhighlight
4:03:21 PM:         at module.exports (/opt/build/repo/node_modules/@11ty/eleventy-plugin-syntaxhighlight/src/PrismLoader.js:11:11)
4:03:21 PM:         at Object.highlight (/opt/build/repo/node_modules/@11ty/eleventy-plugin-syntaxhighlight/src/markdownSyntaxHighlightOptions.js:21:35)
4:03:21 PM:         at Object.default_rules.fence (/opt/build/repo/node_modules/markdown-it/lib/renderer.js:50:27)
4:03:21 PM:         at Renderer.render (/opt/build/repo/node_modules/markdown-it/lib/renderer.js:326:38)
4:03:21 PM:         at MarkdownIt.render (/opt/build/repo/node_modules/markdown-it/lib/index.js:543:24)
4:03:21 PM:         at /opt/build/repo/node_modules/@11ty/eleventy/src/Engines/Markdown.js:72:38
4:03:21 PM:         at processTicksAndRejections (internal/process/task_queues.js:93:5)
4:03:21 PM:         at async Template.render (/opt/build/repo/node_modules/@11ty/eleventy/src/TemplateContent.js:199:22)
4:03:21 PM:         at async Template._getContent (/opt/build/repo/node_modules/@11ty/eleventy/src/Template.js:547:12)
4:03:21 PM:         at async Template.getTemplateMapContent (/opt/build/repo/node_modules/@11ty/eleventy/src/Template.js:732:19)
4:03:21 PM: Copied 59 files / Wrote 0 files in 0.42 seconds (v0.11.0)
4:03:21 PM: npm ERR! code ELIFECYCLE
4:03:21 PM: npm ERR! errno 1
4:03:21 PM: npm ERR! eleventy-high-performance-blog@5.0.2 build: `npm run js-build && eleventy && npm run test`
4:03:21 PM: npm ERR! Exit status 1
4:03:21 PM: npm ERR!
4:03:21 PM: npm ERR! Failed at the eleventy-high-performance-blog@5.0.2 build script.
4:03:21 PM: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
4:03:21 PM: npm ERR! A complete log of this run can be found in:
4:03:21 PM: npm ERR!     /opt/buildhome/.npm/_logs/2020-12-19T08_03_21_227Z-debug.log
```

**Comment by cdeleeuwe** [comment]
Hmm odd, I think this error is not an issue with the plugin, but from what I see in your logs, it's trying to render the files under node_modules. For example in the logs I see ```Having trouble rendering liquid (and markdown) template ./.netlify/plugins/node_modules/node-fetch/README.md```. @nlbao not sure, but maybe you can try configuring your project to exclude the node_modules files?

**Comment by nlbao** [comment]
Hey @cdeleeuwe, thank you for your advice!
I tried to ignore the `.netlify` directory and it works.
It seems like an issue between Netlify & eleventy.
